# --- !Ups

CREATE TABLE PLAY.USER(
   ID BIGINT NOT NULL PRIMARY KEY ,
   FIRST_NAME VARCHAR(255),
   LAST_NAME VARCHAR(255),
   EMAIL VARCHAR(255) NOT NULL UNIQUE,
   PASSWORD VARCHAR(255) NOT NULL ,
   ROLE VARCHAR(255)
);


INSERT INTO PLAY.USER(ID, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, ROLE) VALUES
    (1, 'salma', 'fayez', 'salma@gmail.com', '$2a$10$RRA28oJNPvopDkCAWDXiSera5KLaCXPXiYVdq0qlFef8TVdGHXtvG','USER'),
    (2, 'mariam', 'mohammed', 'mariam@gmail.com', '$2a$10$RRA28oJNPvopDkCAWDXiSera5KLaCXPXiYVdq0qlFef8TVdGHXtvG','ADMIN');

#--- !Downs

DROP TABLE PLAY.USER;